

version: '3.7'

services:
  vault-server:
    image: hashicorp/vault-enterprise:1.10.4-ent
    hostname: vault
    container_name: vault
    network_mode: host
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    volumes:
      - /etc/vault.d/file:/vault/file
      - /etc/vault.d:/vault
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config.hcl
  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    container_name: plex
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
      - PLEX_CLAIM=
      - HOSTNAME="Hashi-Plex"
    volumes:
      - ./files/config:/config
      - ./files/transcodes:/transcode
      - ./files/media:/media